# Copied then modified from https://github.com/mlcommons/medperf/blob/905e9fdeb33e10beb83307cde9d11040e8a33b0b/mkdocs.yml
site_name: COVFEFE
site_url: https://collaborativefederatedlearningtutorials.github.io/website
repo_url: https://github.com/CollaborativeFederatedLearningTutorials/website
repo_name: CollaborativeFederatedLearningTutorials/website
nav:
  - Introduction: index.md
  - Tutorial: tutorial.md

theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - macros

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: True
  - attr_list
  - md_in_html

extra_css:
  - styles/styles.css

extra_javascript:
  - scripts/script.js